# Using `mayavi.mlab`: getting started

**Prabhu Ramachandran**

**Department of Aerospace Engineering, IIT Bombay**
<br/>

**SciPy 2018**

**Austin, Texas, July 2018**


## Outline

- Getting started with `mlab`
- Using `mlab`
   - The basics
   - Animation
- Going deeper
   - The pipeline
   - Data sources


## Getting started with `mlab`


## Overview

* Simple

* Convenient

* Full-featured


## Getting started

With `jupyter`,

```
$ jupyter console
In [1]: %gui qt
```

with IPython,

```
$ ipython --gui=qt
```

or

```
$ ipython
In [1]: %gui qt
```


## Using notebooks

Make sure you have the following code first


In [1]:
%gui qt


* All plots will pop-up a window

* Inline support will be covered later

* Python 2.x may require using: `%gui qt4`

* May need to set env var
   * `export QT_API=pyqt`
   * `export QT_API=pyside`


## Troubleshooting

* Which version of Python?

* Version of VTK?

* Version of Qt?

* Post on slack channel


## Please type along in a fresh Jupyter notebook

** Many of the code blocks below may be empty because we want you to type along and not just execute the cells! **


## Using `mlab`


In [2]:
from mayavi import mlab


Try these


In [ ]:
mlab.test_

In [3]:
mlab.test_contour3d()

In [4]:
mlab.test_contour3d??

## Exploring the view

<img src="MEDIA/m2/contour3d.png" height="60%" />

* Mouse
* Keyboard
* Toolbar
* Mayavi icon ![Mayavi icon](MEDIA/m2/m2_icon.png)


## Using `mlab`: the basics


## `mlab` plotting functions: 0D data
<img src="MEDIA/m2/mlab/points3d_ex.png" height="40%" />


In [5]:
import numpy as np
from numpy import *

In [6]:
t = linspace(0, 2*pi, 50)
u = cos(t)*pi
x, y, z = sin(u), cos(u), sin(t)

In [7]:
mlab.points3d(x, y, z)

## Changing how things look

### Clearing the view


In [11]:
mlab.clf()

### IPython is your friend!


In [9]:
mlab.points3d


* Extra argument: Scalars
* Keyword arguments
* UI


In [13]:
mlab.points3d(x, y, z, t, scale_mode='none')

### 1D data

<img src="MEDIA/m2/mlab/plot3d_ex.png" height="80%"/>


In [14]:
mlab.clf()
mlab.plot3d(x, y, z, t)


Plots lines between the points


## Exercise

Visualize a helical spring with a spherical mass on one of its ends with a
fixed color for both.


## Solution


In [16]:
# %load solutions/02_helix.py
mlab.clf()

t = linspace(0, 10*pi, 1000)
x, y = 0.2*sin(t), 0.2*cos(t)
z = 0.1*t
mlab.plot3d(x, y, z, color=(1, 0, 0))
mlab.points3d(x[-1], y[-1], z[-1])

## An aside: `np.mgrid`


In [17]:
from numpy import mgrid

In [18]:
arange(0, 3, 1)

array([0, 1, 2])

In [21]:
x, y = mgrid[0:3:1, 0:3:1]

In [22]:
linspace(-1, 1, 5)

array([-1. , -0.5,  0. ,  0.5,  1. ])

In [25]:
mgrid[-1:1:5j]

array([-1. , -0.5,  0. ,  0.5,  1. ])

## Example


In [26]:
x, y = mgrid[-1:1:5j, -1:1:5j]
z = x*x + y*y

In [27]:
z

array([[ 2.  ,  1.25,  1.  ,  1.25,  2.  ],
       [ 1.25,  0.5 ,  0.25,  0.5 ,  1.25],
       [ 1.  ,  0.25,  0.  ,  0.25,  1.  ],
       [ 1.25,  0.5 ,  0.25,  0.5 ,  1.25],
       [ 2.  ,  1.25,  1.  ,  1.25,  2.  ]])

## 2D data: `mlab.surf`
<img src="MEDIA/m2/mlab/surf_ex.png" height="30%" />


In [28]:
x, y = mgrid[-3:3:100j,-3:3:100j]
z = sin(x*x + y*y)

In [29]:
mlab.clf()
mlab.surf(x, y, z)

Assumes the points are rectilinear


## 2D data: `mlab.contour_surf`

<img src="MEDIA/m2/mlab/contour_surf_ex.png" height="50%"/>


In [30]:
x, y = mgrid[-3:3:100j,-3:3:100j]
z = sin(x*x + y*y)

In [31]:
mlab.clf()
mlab.contour_surf(x, y, z)

Assumes the points are rectilinear


## 2D data: `mlab.mesh`


In [32]:
mlab.clf()
mlab.mesh(x, y, z)


Points need not be regular


In [33]:
x, y = mgrid[-3:3:100j,-3:3:100j]
z = (x*x + y*y)*0.1
mlab.clf()
mlab.mesh(sin(x), cos(y), z)

Go ahead and experiment with other functions!


In [34]:
mlab.clf()
mlab.mesh(sin(x), cos(y), sin(x*y))

## Exercise

Plot the surface of a unit sphere using `mlab.mesh`  with a
wireframe.


## Solution


In [36]:
# %load -r 5-10 solutions/02_sphere.py
phi, theta = np.mgrid[0:pi:20j, 0:2*pi:20j]
x = sin(phi)*cos(theta)
y = sin(phi)*sin(theta)
z = cos(phi)
mlab.clf()
mlab.mesh(x, y, z, representation='wireframe')

## 2D data: `mlab.triangular_mesh`

<img src="MEDIA/m2/mlab/triangular_mesh_ex.png"/>


In [37]:
x, y, z = [[0., 1., 1], [0., 0, 1], [0., 0, 0]]
t = [[0, 1, 2], ]

In [38]:
points = np.array([[0., 0, 0], [1, 0, 0], [1, 1, 0]])
x, y, z = points.T

In [39]:
mlab.clf()
mlab.triangular_mesh(x, y, z, t)

Explicitly specify the triangles


## Exercise

Create a simple pyramid composed of triangles and plot it.


## Solution


In [41]:
# %load solutions/02_pyramid.py
x = [0., 1, 1, 0, 0.5]
y = [0., 0, 1, 1, 0.5]
z = [0., 0, 0, 0, 1]
t = [[0, 1, 4], [1, 2, 4],
     [2, 3, 4], [3, 0, 4]]

mlab.clf()
mlab.triangular_mesh(
    x, y, z, t
)

## 2D data: `mlab.imshow`


In [42]:
s = np.random.random((2<<12, 2<<12))
s.shape

(8192, 8192)

In [43]:
mlab.clf()
mlab.imshow(s)

Do not try this with `matplotlib`!


## 3D data

<img src="MEDIA/m2/mlab/contour3d.png" width="35%" height="50%" />


In [44]:
x, y, z = mgrid[-5:5:64j, -5:5:64j, -5:5:64j]
mlab.clf()
mlab.contour3d(x*x*0.5 + y*y + z*z*2)

## 3D data: `volume_slice`

<img src="MEDIA/m2/mlab/volume_slice.png" width="35%" height="50%" />


In [45]:
x, y, z = np.mgrid[-5:5:64j, -5:5:64j, -5:5:64j]
mlab.clf()
mlab.volume_slice(x, y, z, x*x*0.5 + y*y + z*z*2)

## 3D vector data: `mlab.quiver3d`

<img src="MEDIA/m2/mlab/quiver3d_ex.png" width="35%" height="50%"/>


In [46]:
mlab.clf()
mlab.test_quiver3d()

In [47]:
#o = mlab.quiver3d(x, y, z, u, v, w)
o = mlab.quiver3d(1, 1, 1, 0, 5, 5)

## 3D vector data: `mlab.flow`


In [48]:
x, y, z = mgrid[-2:3:100j, -2:3:100j, -2:3:100j]
r = sqrt(x**2 + y**2 + z**4)
u = y*sin(r)/(r+0.001)
v = -x*sin(r)/(r+0.001)
w = ones_like(z)*0.1
mlab.clf()
obj = mlab.flow(x, y, z, u, v, w,
                seedtype='plane')

## Exercise: Lorenz equation

\begin{align}
\frac{d x}{dt} &= s (y-x) \\
\frac{d y}{d t} &= rx -y -xz \\
\frac{d z}{d t} &= xy - bz \\
\end{align}

Let $ s=10,r=28, b=8./3$.


In [49]:
x, y, z = mgrid[-50:50:20j, -50:50:20j, -10:60:20j]

## Exercise

Consider the region of interest


In [50]:
x, y, z = mgrid[-50:50:20j, -50:50:20j, -10:60:20j]

* Hint: use `mlab.quiver3d`
* Explore arguments to make the visualization better


## Solution


In [51]:
def lorenz(x, y, z, s=10.,r=28., b=8./3):
    u = s*(y-x)
    v = r*x -y - x*z
    w = x*y - b*z
    return u, v, w

In [53]:
# %load solutions/02_lorenz.py
x, y, z = mgrid[-50:50:20j,-50:50:20j, -10:60:20j]
u, v, w = lorenz(x, y, z)

mlab.clf()
mlab.quiver3d(
    x, y, z, u, v, w,
    scale_factor=0.01,
    mask_points=5
)

## Another exercise

* Try the same with `mlab.flow`
* Use the UI to configure things


## Solution


In [55]:
mlab.clf()
mlab.flow(x, y, z, u, v, w)

## Digression exercise
Plot the trajectory of a point starting at (10, 50, 50) for 50 seconds.


## Solution


In [56]:
from scipy.integrate import odeint

In [58]:
# %load solutions/02_lorenz_traj.py
def lorenz_ode(state, t):
    x, y, z = state
    return np.array(lorenz(x, y, z))

t = np.linspace(0., 50., 2000)
r = odeint(
    lorenz_ode, (10., 50., 50.), t
)

#x, y, z = r[:,0], r[:,1], r[:,2]
x, y, z = r.T
mlab.plot3d(x, y, z, t, tube_radius=None)

## Issues and solutions

* Basic visualization: not very useful

* Tweak parameters: `mask_points, scale_factor`
* Explore parameters on UI

* `mlab.flow`  is a lot better!

**Good visualization involves work**


## Other utility functions

* `gcf` : get current figure



* `savefig`, `figure`



* `axes`, `outline`



* `title`, `xlabel, ylabel, zlabel`



* `colorbar, scalarbar, vectorbar`



* `show` : Standalone mlab scripts



* `orientation_axes`, `text3d`


## More utility functions

* `show_pipeline`
* `view, roll, yaw, move`
* Others, see UG


## Setting the view


In [ ]:
print(mlab.view())
mlab.view(azimuth=60, elevation=90, distance=100, focalpoint=None)

## Exercise

Create a standalone Python script complete with axes, labels and a
colorbar and save a png image of the rendered scene. Also show the window
for a user to see the final plot and interact with it. Use any existing
plot you have already made for this.


## Solution


In [ ]:
%load solutions/02_standalone.py